[project]
name = "cd-lastpass-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Craig Davis", email = "craig@pienso.com" }]
requires-python = ">=3.12"
dependencies = [
  "click>=8.4.2",
  "dill>=0.4.1",
  "lastpasslib>=1.2.2",
  "loguru>=0.7.3",
  "pydantic>=2.13.4",
  "rich-click>=1.9.8",
]

[project.scripts]
lastpass = "cd_lastpass_cli:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
package = true
managed = true
# [tool.uv.build-backend]
# data = { scripts = "bin" }

[dependency-groups]
dev = [
  "coverage>=7.15.2",
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "ruff>=0.16.0",
  "ty>=0.0.63",
]
